import { StructuredText } from 'react-datocms/structured-text';
import { SectionContainer } from '@components/ui/custom-container';
import { Badge, Calendar, ChevronLeft, TagIcon } from 'lucide-react';
import { renderNodeRule } from 'react-datocms';
import {
  isCode,
  isHeading,
  isParagraph,
  isRoot,
} from 'datocms-structured-text-utils';
import CodeBlock from '@components/codeBlock';
import Link from 'next/link';

const data = {
  data: {
    technicalLedger: {
      title: 'System Architecture: Scalable RAG Pipelines',
      excerpt:
        'Architecting a Retrieval-Augmented Generation (RAG) system requires more than just a vector database. This note explores the critical bottlenecks in document chunking strategies, the importance of re-ranking models in high-density datasets, and how to utilize Next.js Edge Runtime to stream AI responses with sub-100ms latency. We deep dive into the trade-offs between Pinecone and pgvector for enterprise-scale deployments.',
      date: '2026-02-15',
      category: 'Architecture',
      tags: [
        {
          id: 'SzynrKRMTiGtYj15GZI45g',
          tag: 'AI',
        },
        {
          id: 'YM-rGjbnTV6RhkzFP4ZRwA',
          tag: 'VectorDB',
        },
        {
          id: 'FCMERxj8RCSgK3M1edYvLQ',
          tag: 'Node.js',
        },
      ],
      fullNote: {
        blocks: [],
        inlineBlocks: [],
        links: [],
        value: {
          schema: 'dast',
          document: {
            type: 'root',
            children: [
              {
                type: 'heading',
                level: 2,
                children: [
                  {
                    type: 'span',
                    value: ' Introduction',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    value:
                      'Retrieval-Augmented Generation (RAG) has become the gold standard for grounding LLMs in private data. However, moving from a local PoC to a production-scale pipeline introduces significant challenges in latency and retrieval accuracy.',
                  },
                ],
              },
              {
                type: 'heading',
                level: 3,
                children: [
                  {
                    type: 'span',
                    value: 'The Retrieval Dilemma',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    value:
                      ' Most developers start with simple cosine similarity. While effective for small datasets, it fails when the context window becomes cluttered with semantically similar but irrelevant noise. ',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    marks: ['strong'],
                    value: 'Hybrid Search: ',
                  },
                  {
                    type: 'span',
                    value:
                      'Combining keyword-based BM25 with vector embeddings.',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    marks: ['strong'],
                    value: 'Re-ranking:',
                  },
                  {
                    type: 'span',
                    value:
                      ' Using a Cross-Encoder to validate the top-k results before feeding them to the LLM.',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    marks: ['strong'],
                    value: 'Scalability at the Edge',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    value:
                      'Using Next.js 16, we can leverage Edge Functions to handle the embedding generation. This offloads the compute from the main server and allows us to stream chunks directly to the client as they are generated by the model.',
                  },
                ],
              },
              {
                code: "export const config = { runtime: 'edge' };\n\nasync function getEmbeddings(text: string) {\n\n // Implementation of edge-optimized vectorization\n}",
                type: 'code',
                language: 'typescript',
              },
              {
                type: 'heading',
                level: 3,
                children: [
                  {
                    type: 'span',
                    value: ' Infrastructure Considerations',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    value:
                      'When selecting a Vector Database, consider the following metrics:',
                  },
                ],
              },
              {
                type: 'list',
                style: 'numbered',
                children: [
                  {
                    type: 'listItem',
                    children: [
                      {
                        type: 'paragraph',
                        children: [
                          {
                            type: 'span',
                            marks: ['strong'],
                            value: 'Query Per Second (QPS):',
                          },
                          {
                            type: 'span',
                            value:
                              ' How many retrievals can happen concurrently?',
                          },
                        ],
                      },
                    ],
                  },
                  {
                    type: 'listItem',
                    children: [
                      {
                        type: 'paragraph',
                        children: [
                          {
                            type: 'span',
                            marks: ['strong'],
                            value: 'Indexing Time:',
                          },
                          {
                            type: 'span',
                            value:
                              ' How long before a new document is searchable?',
                          },
                        ],
                      },
                    ],
                  },
                  {
                    type: 'listItem',
                    children: [
                      {
                        type: 'paragraph',
                        children: [
                          {
                            type: 'span',
                            marks: ['strong'],
                            value: 'Cost of Multi-tenancy:',
                          },
                          {
                            type: 'span',
                            value: ' Isolated namespaces for different users.',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                type: 'heading',
                level: 3,
                children: [
                  {
                    type: 'span',
                    value: 'Conclusion',
                  },
                ],
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'span',
                    value:
                      "A scalable RAG pipeline is not a 'set and forget' system. It requires continuous monitoring of retrieval precision and constant fine-tuning of the chunking overlap (typically 10-15%) to ensure context is never lost at the boundaries.",
                  },
                ],
              },
            ],
          },
        },
      },
    },
  },
};
interface TechnicalNotePageProps {
  locale?: string;
}

const TechnicalLedger = ({ locale }: TechnicalNotePageProps) => {
  const { technicalLedger } = data.data;
  if (!technicalLedger) return null;

  return (
    <div className="flex flex-col gap-6">
      <SectionContainer
        disableShine
        disablePattern
        className="w-full rounded-none border-t-0"
      >
        <Link
          href={`/${locale}/technical-ledgers`} // Navigates back to your listing page
          className="group text-muted-foreground hover:text-primary mb-8 flex w-fit items-center gap-1 text-sm font-medium transition-colors"
        >
          <ChevronLeft className="size-4 transition-transform group-hover:-translate-x-1" />
          Back to Ledger
        </Link>

        <h1 className="mb-4 text-2xl font-bold tracking-tight md:text-3xl">
          {technicalLedger.title}
        </h1>

        <div className="flex items-center gap-1">
          <Badge className="tracking-widest" size={15} />
          <span className="text-primary text-sm font-bold capitalize">
            {technicalLedger.category}
          </span>
        </div>

        <div className="text-muted-foreground flex flex-wrap items-center gap-6 text-sm">
          <div className="flex items-center gap-2">
            <Calendar className="size-4" />
            {new Date(technicalLedger.date).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </div>

          {technicalLedger.tags && technicalLedger.tags.length > 0 && (
            <div className="flex items-center gap-2">
              <TagIcon className="size-4" />
              <div className="flex gap-2">
                {technicalLedger.tags.map((tag) => (
                  <span
                    key={tag.id}
                    className="hover:text-primary cursor-default"
                  >
                    #{tag.tag || 'tech'}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </SectionContainer>

      {/* Content Section */}
      <div className="flex min-h-[calc(100lvh-18rem)] flex-col gap-4 p-4">
        <article>
          <StructuredText
            data={technicalLedger.fullNote}
            customNodeRules={[
              renderNodeRule(isCode, ({ node, key }) => {
                return (
                  <CodeBlock
                    key={key}
                    code={node.code}
                    language={node.language!}
                  />
                );
              }),
              renderNodeRule(isParagraph, ({ children, key, ancestors }) => {
                if (isRoot(ancestors[0])) {
                  return (
                    <p key={key} className="my-2 text-sm">
                      {children}
                    </p>
                  );
                } else {
                  return (
                    <p key={key} className="my-1 text-sm">
                      {children}
                    </p>
                  );
                }
              }),
              renderNodeRule(
                isHeading,
                ({ node, children, key, ancestors }) => {
                  switch (node.level) {
                    case 1:
                      return (
                        <h1 key={key} className="my-4 text-2xl font-bold">
                          {children}
                        </h1>
                      );
                    case 2:
                      return (
                        <h2 key={key} className="my-3 text-xl font-bold">
                          {children}
                        </h2>
                      );
                    case 3:
                      return (
                        <h3 key={key} className="my-2 text-lg font-semibold">
                          {children}
                        </h3>
                      );
                    default:
                      return (
                        <p key={key} className="text-sm font-bold">
                          {children}
                        </p>
                      );
                  }
                }
              ),
            ]}
          />
        </article>
      </div>
    </div>
  );
};

export default TechnicalLedger;
